### ISSUE TITLE
SqliteDict doesn't seem to accept frozensets as keys.

### ISSUE THREAD

**Issue by blaiseli** [piskvorky/sqlitedict#22]
Consider the following script:

    #!/usr/bin/env python
    from sqlitedict import SqliteDict
    d = SqliteDict("test.sqlite")
    d[frozenset(["c", "d"])] = "ab"

An exception is raised when executing it:

    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
        self.run()
      File "<my_home>/.local/lib/python2.7/site-packages/sqlitedict.py", line 296, in run
        cursor.execute(req, arg)
    InterfaceError: Error binding parameter 0 - probably unsupported type.

**Comment by piskvorky** [comment]
That's correct. Sqlitedict's API says it supports **string** keys. Quick solution for you: `d[str(sorted(x))] = ...`

I'm not sure how much work it would be to extend the API to other key types, such as `frozenset`. Let me know if you want to look into it.
