### ISSUE TITLE
sets as value in an SqliteDict not updated

### ISSUE THREAD

**Issue by blaiseli** [piskvorky/sqlitedict#23]
Is the following behaviour expected?

    >>> from sqlitedict import SqliteDict
    >>> d = SqliteDict("test.sqlite", autocommit=True)
    >>> d["a"] = set([])
    >>> d["a"].add(1)
    >>> d["a"]
    set([])
    >>> d.commit()
    >>> d["a"]
    set([])
    >>> d["a"].add(1)
    >>> d.commit()
    >>> d["a"]
    set([])
    >>>

**Comment by blaiseli** [comment]
Ah, it seems that this point is addressed in the doc.

**Comment by piskvorky** [comment]
Indeed, it is :)
