### ISSUE TITLE
Saving tuples as keys using sqlitedict

### ISSUE THREAD

**Issue by ziky90** [piskvorky/sqlitedict#25]
This issue is more a new feature idea.

It would be nice to be able to use Python tuples as keys as you can do it in standard Python dicts. My idea is to do something like serialisation from tuple to string (for example via `user_defined_character.join(tuple)` or via some user defined conversion function). 

For querying there would be used just the same transformation function and for keys reconstruction there might be something like, either `key.split(user_defined_character)` or some other user defined conversion function.

**Comment by jquast** [comment]
I believe this would be solved by #19, which believe it or not I plan to get to very soon.

**Comment by piskvorky** [comment]
I believe it! :)

Now that I think of it, why not just `pickle.dumps` the keys as well?

That is, keys are internally always strings (=pickle dumps), and encode/decode of the keys that user gives happens transparently.

That will allow arbitraty objects as keys (anything pickleable). Strings or tuples or whatever will no longer a special case, and will require no special action from users.

Or am I missing something?

**Comment by piskvorky** [comment]
Handled in separate pull requests, using pickle for encoding arbitrary key objects.
