### ISSUE TITLE
setdefault does not work as for dict

### ISSUE THREAD

**Issue by ziky90** [piskvorky/sqlitedict#34]
When I use sqlitedict I see that there is no working `setdefault` as I am used to from standard dict.

My not working code looks as follows:

```
with SqliteDict(d, autocommit=True) as c:
    c.setdefault(k, []).append("d")
```

My working code looks as:

```
if k in c:
    l = c[k]
    l.append("d")
    c[k] = l
else:
    c[k] = ["d"]
```

**NOTE:**
Even this did not work for me:

```
if k in c:
    l = c[k]
    l.append("d")
else:
    c[k] = ["d"]
```

I can see that there is only inherited `setdefault` and there are not tests for it. Should `setdefault` work? If not is that wanted as new feature?

**Comment by piskvorky** [comment]
See the **Beware** section in the README: https://github.com/piskvorky/sqlitedict#documentation

It cannot be added as a new feature, this limitation is due to semantics of the Python language itself.
