### ISSUE TITLE
.terminate() failed to delete file xx.sqlite, clear() can not reset the file size...

### ISSUE THREAD

**Issue by ClericPy** [piskvorky/sqlitedict#42]
.terminate() raise an error for it's in use when del the file, and after clear() the file size is still as large as before(43MB, not 3KB).
Indeed I prefer sqlitedict to tinydb...

**Comment by piskvorky** [comment]
Not sure I understand -- `terminate()` closes the file and then attempts to delete it.

What problem exactly are you reporting -- can you post the full log, at DEBUG level?

And also your OS, version of python, version of sqlitedict. Thanks!

**Comment by ClericPy** [comment]
Thanks for your answer & sorry for bother you... there is one python process is using that db and never be killed(maybe some sub-process), so it is not a issue any more.
by the way, may I ask one more question, the file size didn't release after I used db.clear(), even it had nothing in.

**Comment by piskvorky** [comment]
Alright, closing this issue.

Regarding `clear()`: it clears (deletes) [all rows in a table](https://github.com/piskvorky/sqlitedict/blob/master/sqlitedict.py#L261), but [doesn't VACUUM the space](http://stackoverflow.com/questions/2143800/change-sqlite-file-size-after-delete-from-table). I think that the vacuum operation was sometimes causing trouble we though was unnecessary. Feel free to call VACUUM manually (or delete/terminate the entire DB file and start from scratch).

**Comment by ClericPy** [comment]
You really did me a big favor, and I learned much from here, thanks
conn=sqlite3.connect('xx.sqlite')
conn.execute("VACUUM")
conn.execute("VACUUM")
conn.execute("VACUUM")
conn.close()
makes good

**Comment by piskvorky** [comment]
No problem. Enjoy!

**Comment by Naeemkh** [comment]
@ClericPy 
Thanks for the response. Is there any reason to execute the "VACUUM" three times. It seems one time does the work. Please let me know your thoughts.
